# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "28b20b94bc527381392af6771293bd9f"
name = "TrackProfit"
handle = "trackprofit-2"
application_url = "https://trackprofit-d483e888978b.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "app/scopes_update",
  "inventory_items/update",
  "inventory_levels/update",
  "products/create",
  "products/delete",
  "products/update",
  "orders/create",
  "orders/updated",
  "orders/cancelled"
]
  uri = "https://trackprofit-d483e888978b.herokuapp.com/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,read_inventory,read_orders,read_products,write_inventory,write_products,read_customers,read_fulfillments,read_shipping,write_orders"

[auth]
redirect_urls = [
  "https://trackprofit-d483e888978b.herokuapp.com/auth/callback",
  "https://trackprofit-d483e888978b.herokuapp.com/api/auth/callback",
  "https://trackprofit-d483e888978b.herokuapp.com/auth/shopify/callback"
]

[pos]
embedded = false
