# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d814a6f1bb99422cba1f045cdaf01e0"
name = "TrackProfit"
handle = "trackprofit-2"
application_url = "https://trackprofit-ae3531c1607b.herokuapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "inventory_items/update",
  "inventory_levels/update",
  "orders/cancelled",
  "orders/create",
  "orders/updated",
  "products/create",
  "products/delete",
  "products/update"
]
  uri = "https://trackprofit-ae3531c1607b.herokuapp.com/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_inventory,read_orders,read_products,write_inventory,write_products"

[auth]
redirect_urls = [
  "https://trackprofit-ae3531c1607b.herokuapp.com/auth/callback",
  "https://trackprofit-ae3531c1607b.herokuapp.com/api/auth/callback",
  "https://trackprofit-ae3531c1607b.herokuapp.com/auth/shopify/callback"
]
